name: Unit tests

on:
  push:
    branches:
      - feature/*
      - chore/*
  schedule:
    - cron: '0 */6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: |
          xcodebuild clean test -project WhiteFlowerFactory.xcodeproj -scheme WhiteFlowerFactory -destination 'platform=iOS Simulator,name=iPhone 11 Pro'
          xcodebuild test -project WhiteFlowerFactory.xcodeproj -scheme WhiteFlowerFactory -destination 'platform=OS X,arch=x86_64'
          